project:
  type: website

website:
  navbar:
    logo: "images/logo_name.png"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    left:

      - text: Study Area
        href: studyarea.qmd
      - text: Methodology
        href: methodology.qmd
      - text: EDA
        href: project.qmd
      - text: "Landslide Susceptibility Models"
        menu:
        - href: explanatorymodelling.qmd
          text: "Explanatory Modelling"
        - href: predictivemodelling.qmd
          text: "Predictive Modelling"
      - text: Research Poster
        href: poster.qmd

  page-footer:
    background: primary
    left: "What Causes Landslides? Explanatory Landslide Susceptibility Modelling of Valtellina Valley, Lombardy Region, Italy"
format:
  html:
    theme: pulse
    css: [styles.css, logo.css]
    toc: true
    
editor: visual

