project:
  type: website

website:
  navbar:
    logo: "images/logo_name.png"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    left:

      - text: Study Area
        href: studyarea.qmd
      - text: Methodology
        href: methodology.qmd
      - text: Data Preview
        href: data.qmd
      - text: "Landslide Susceptibility Models"
        menu:
        - href: explanatorymodelling.qmd
          text: "Explanatory Modelling"
        - href: predictivemodelling.qmd
          text: "Predictive Modelling"
      - text: Research Poster
        href: poster.qmd
      - text: "Final Slides"
        href: final_presentation.qmd

  page-footer:
    background: primary
    left: "Is There a Space in Landslide Susceptibility Modelling: A Case Study of Valtellina Valley, Northern Italy"
format:
  html:
    theme: pulse
    css: [styles.css, logo.css]
    toc: true
    
editor: visual

