---
title: "Project"
author:
  - name: Khant Min Naing
  - name: Mei Yi Victoria Grace Ann
date: 01-07-2024
date-modified: "last-modified"
categories:
  - R
  - sf
  - ggplot2
output:
  distill::distill_article:
    code_folding: false
    toc: true
    self_contained: false
---

## Set Up {style="color: #603494;"}
```{r, code_folding=FALSE,warning=FALSE}
library(sp)
library(raster) 
library(elevatr)
library(sf)
library(RColorBrewer)
library(classInt)
library(ggplot2)
library(terra)
library(tidyr)
library(paletteer)
library(cowplot)
library(dplyr)
```

## Import {style="color: #603494;"}

```{r, code_folding=FALSE}
valtellina <- read_sf(dsn = "./data/vector", layer = "valtellina")
precipitation <-raster("data/raster/avgprecipitation_mm.tif")
```


## Fixing CRS References {style="color: #603494;"}
```{r, code_folding=FALSE,results='hide'}

valtellina <- st_set_crs(valtellina,32632)
precipitation <- projectRaster(precipitation, crs = crs(valtellina))
```


## Create Database {style="color: #603494;"}
```{r, code_folding=FALSE}

precipitation_df <- as.data.frame(precipitation,xy=TRUE)%>%drop_na()
tail(precipitation_df)
```

## Plot with ggplot2 {style="color: #603494;"}

```{r, code_folding=FALSE}

ggplot()+
  geom_raster(aes(x=x,y=y,fill=avgprecipitation_mm),data=precipitation_df)+
  geom_sf(fill='transparent',data=valtellina)+
  scale_fill_gradientn('avg precipitation \n(mm)', colours=c("#eff635","#e4c838","#99bf3e","#61adab","#5071ea","#4225df","#3310a2"))+
  coord_sf(expand=FALSE)+
  labs(x='Longitude',y='Latitude',
       title="Average Precipitation Map",
       subtitle='Valtellina Valley, Italy',
       caption='Source: Zindi') +
  cowplot::theme_cowplot()+
  theme(panel.grid.major = element_line(color = gray(.5),
                                        linetype = 'dashed',
                                        linewidth = 0.5),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill=NA,color = 'black'),
        panel.ontop = TRUE,
        axis.title.x = element_text(size = 10), 
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        legend.title = element_text(size = 10))
```
