<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Khant Min Naing">
<meta name="author" content="Ann Mei Yi Victoria Grace">
<meta name="dcterms.date" content="2024-02-19">

<title>Slope-Based Stratified Sampling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
<link rel="stylesheet" href="logo.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./images/logo_name.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./studyarea.html" rel="" target="">
 <span class="menu-text">Study Area</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./methodology.html" rel="" target="">
 <span class="menu-text">Methodology</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./project.html" rel="" target="">
 <span class="menu-text">EDA</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-model-development" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Model Development</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-model-development">    
        <li>
    <a class="dropdown-item" href="./gwsmodelling.html" rel="" target="">
 <span class="dropdown-text">Parametric Testing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./slopesampling.html" rel="" target="">
 <span class="dropdown-text">Slope Sampling</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./research.html" rel="" target="">
 <span class="menu-text">Research Paper</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#slope-based-stratified-sampling" id="toc-slope-based-stratified-sampling" class="nav-link active" data-scroll-target="#slope-based-stratified-sampling">Slope-Based Stratified Sampling</a>
  <ul class="collapse">
  <li><a href="#import-packages" id="toc-import-packages" class="nav-link" data-scroll-target="#import-packages">1.0 Import Packages</a></li>
  <li><a href="#import-data" id="toc-import-data" class="nav-link" data-scroll-target="#import-data">2.0 Import Data</a></li>
  <li><a href="#slope-sampling" id="toc-slope-sampling" class="nav-link" data-scroll-target="#slope-sampling">3.0 Slope Sampling</a>
  <ul class="collapse">
  <li><a href="#calculating-quartiles" id="toc-calculating-quartiles" class="nav-link" data-scroll-target="#calculating-quartiles">3.1 Calculating Quartiles</a></li>
  <li><a href="#subseting-dataset-into-quartile-based-samples" id="toc-subseting-dataset-into-quartile-based-samples" class="nav-link" data-scroll-target="#subseting-dataset-into-quartile-based-samples">3.2 Subseting Dataset into Quartile-based Samples</a></li>
  <li><a href="#plotting-slope-stratified-datasets" id="toc-plotting-slope-stratified-datasets" class="nav-link" data-scroll-target="#plotting-slope-stratified-datasets">3.3 Plotting Slope-Stratified Datasets</a></li>
  <li><a href="#creating-correlation-matrix" id="toc-creating-correlation-matrix" class="nav-link" data-scroll-target="#creating-correlation-matrix">3.4 Creating Correlation Matrix</a></li>
  </ul></li>
  <li><a href="#logistic-regression-modelling" id="toc-logistic-regression-modelling" class="nav-link" data-scroll-target="#logistic-regression-modelling">4.0 Logistic Regression Modelling</a>
  <ul class="collapse">
  <li><a href="#logistic-regression-model-1-slope-cut-off-1st-quartile" id="toc-logistic-regression-model-1-slope-cut-off-1st-quartile" class="nav-link" data-scroll-target="#logistic-regression-model-1-slope-cut-off-1st-quartile">4.1 Logistic Regression Model 1 (Slope Cut-off = 1st Quartile)</a></li>
  <li><a href="#logistic-regression-model-2-slope-cut-off-2nd-quartile" id="toc-logistic-regression-model-2-slope-cut-off-2nd-quartile" class="nav-link" data-scroll-target="#logistic-regression-model-2-slope-cut-off-2nd-quartile">4.2 Logistic Regression Model 2 (Slope Cut-off = 2nd Quartile)</a></li>
  <li><a href="#logistic-regression-model-3-slope-cut-off-3rd-quartile" id="toc-logistic-regression-model-3-slope-cut-off-3rd-quartile" class="nav-link" data-scroll-target="#logistic-regression-model-3-slope-cut-off-3rd-quartile">4.3 Logistic Regression Model 3 (Slope Cut-off = 3rd Quartile)</a></li>
  <li><a href="#logistic-regression-model-4-slope-cut-off-4th-quartile" id="toc-logistic-regression-model-4-slope-cut-off-4th-quartile" class="nav-link" data-scroll-target="#logistic-regression-model-4-slope-cut-off-4th-quartile">4.4 Logistic Regression Model 4 (Slope Cut-off = 4th Quartile)</a></li>
  <li><a href="#logistic-regression-model-5-slope-cut-off-25" id="toc-logistic-regression-model-5-slope-cut-off-25" class="nav-link" data-scroll-target="#logistic-regression-model-5-slope-cut-off-25">4.5 Logistic Regression Model 5 (Slope Cut-off = 25)</a></li>
  <li><a href="#logistic-regression-model-6-slope-cut-off-20" id="toc-logistic-regression-model-6-slope-cut-off-20" class="nav-link" data-scroll-target="#logistic-regression-model-6-slope-cut-off-20">4.6 Logistic Regression Model 6 (Slope Cut-off = 20)</a></li>
  <li><a href="#logistic-regression-model-7-slope-cut-off-15" id="toc-logistic-regression-model-7-slope-cut-off-15" class="nav-link" data-scroll-target="#logistic-regression-model-7-slope-cut-off-15">4.7 Logistic Regression Model 7 (Slope Cut-off = 15)</a></li>
  </ul></li>
  <li><a href="#geographically-weighted-logistic-regression" id="toc-geographically-weighted-logistic-regression" class="nav-link" data-scroll-target="#geographically-weighted-logistic-regression">5.0 Geographically Weighted Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#calculating-adaptive-bandwidth" id="toc-calculating-adaptive-bandwidth" class="nav-link" data-scroll-target="#calculating-adaptive-bandwidth">5.1 Calculating Adaptive Bandwidth</a></li>
  <li><a href="#building-geographically-weighted-logistic-regression-model" id="toc-building-geographically-weighted-logistic-regression-model" class="nav-link" data-scroll-target="#building-geographically-weighted-logistic-regression-model">5.2 Building Geographically Weighted Logistic Regression Model</a></li>
  <li><a href="#model-summary" id="toc-model-summary" class="nav-link" data-scroll-target="#model-summary">5.3 Model Summary</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Slope-Based Stratified Sampling</h1>
  <div class="quarto-categories">
    <div class="quarto-category">R</div>
    <div class="quarto-category">sf</div>
    <div class="quarto-category">gwmodel</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Khant Min Naing </p>
             <p>Ann Mei Yi Victoria Grace </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 19, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">February 21, 2024</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="slope-based-stratified-sampling" class="level1">
<h1>Slope-Based Stratified Sampling</h1>
<section id="import-packages" class="level2">
<h2 class="anchored" data-anchor-id="import-packages">1.0 Import Packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sp, sf, st, spdep, raster, spatstat, tmap, devtools,vtable,ggplot2,egg, corrplot, patchwork, ggstats, ggstatsplot, GWmodel, tidyverse, gtsummary,vtable, sjPlot, sjmisc, sjlabelled, tableHTML, olsrr, car, blorr,ISLR, klaR,pROC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="import-data" class="level2">
<h2 class="anchored" data-anchor-id="import-data">2.0 Import Data</h2>
<p>We will import datasets used for this sampling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>valtellina <span class="ot">&lt;-</span> <span class="fu">read_sf</span>(<span class="at">dsn =</span> <span class="st">"./data/vector"</span>, <span class="at">layer =</span> <span class="st">"valtellina"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>train_grids_v4 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/IS485-Landslide/data/aspatial/train_grid_v4.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="slope-sampling" class="level2">
<h2 class="anchored" data-anchor-id="slope-sampling">3.0 Slope Sampling</h2>
<section id="calculating-quartiles" class="level3">
<h3 class="anchored" data-anchor-id="calculating-quartiles">3.1 Calculating Quartiles</h3>
<p>First, we will extract the <strong><code>Slope_Angle</code></strong> column from the <strong><code>train_grids_v4</code></strong> data frame and assigning it to the variable <strong><code>slope_angle</code></strong>.</p>
<p>Next we will calculate the quartiles of the <strong><code>slope_angle</code></strong> data such as minimum (0th percentile), first quartile (25th percentile), median (50th percentile), third quartile (75th percentile), and maximum (100th percentile). This helps us understand the distribution of slope angles in the data set.</p>
<p>The <strong><code>quantile</code></strong> function in R calculates the specified quantiles of a data set. The <strong><code>probs</code></strong> argument specifies the probabilities for which quantiles are required, and <strong><code>seq(0, 1, 1/4)</code></strong> generates a sequence of numbers from 0 to 1 in increments of 1/4.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>slope_angle <span class="ot">&lt;-</span> train_grids_v4<span class="sc">$</span>Slope_Angle</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(slope_angle, <span class="at">probs =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      0%      25%      50%      75%     100% 
 0.00000 18.41368 30.34639 38.54599 82.91669 </code></pre>
</div>
</div>
</section>
<section id="subseting-dataset-into-quartile-based-samples" class="level3">
<h3 class="anchored" data-anchor-id="subseting-dataset-into-quartile-based-samples">3.2 Subseting Dataset into Quartile-based Samples</h3>
<p>Based on the quartile values that we have calculated, we will now subset the original dataset into four namely <code>sample_Q1</code>, <code>sample_Q2</code>, <code>sample_Q3</code> &amp; <code>sample_Q4</code>.</p>
<ul>
<li><p>For <strong><code>sample_Q1</code></strong>, we select all rows where <strong><code>Slope_Angle</code></strong> is less than 18.41368. This represents the first quartile of the data.</p></li>
<li><p>For <strong><code>sample_Q2</code></strong>, we select all rows in <strong><code>new_train</code></strong> where <strong><code>Slope_Angle</code></strong> is less than 30.34639.</p></li>
<li><p>For <strong><code>sample_Q3</code></strong>, we select all rows where <strong><code>Slope_Angle</code></strong> is less than 38.54599.</p></li>
<li><p>Finally, for <strong><code>sample_Q4</code></strong>, we select all rows where <strong><code>Slope_Angle</code></strong> is less than or equal to 82.91669.</p></li>
</ul>
<p>Finally, I’m using the <strong><code>nrow</code></strong> function to count the number of rows in each subset. This gives us the number of sample size in each quartile.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>sample_Q1 <span class="ot">&lt;-</span> <span class="fu">subset</span>(train_grids_v4,Slope_Angle <span class="sc">&lt;</span> <span class="fl">18.41368</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>new_train <span class="ot">&lt;-</span> <span class="fu">subset</span>(train_grids_v4,Slope_Angle <span class="sc">&gt;=</span> <span class="fl">18.41368</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>sample_Q2 <span class="ot">&lt;-</span> <span class="fu">subset</span>(new_train,Slope_Angle <span class="sc">&lt;</span> <span class="fl">30.34639</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>new_train <span class="ot">&lt;-</span> <span class="fu">subset</span>(new_train,Slope_Angle <span class="sc">&gt;=</span> <span class="fl">30.34639</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>sample_Q3 <span class="ot">&lt;-</span> <span class="fu">subset</span>(new_train,Slope_Angle <span class="sc">&lt;</span> <span class="fl">38.54599</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>new_train <span class="ot">&lt;-</span> <span class="fu">subset</span>(new_train,Slope_Angle <span class="sc">&gt;=</span> <span class="fl">38.54599</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>sample_Q4 <span class="ot">&lt;-</span> <span class="fu">subset</span>(new_train,Slope_Angle <span class="sc">&lt;=</span> <span class="fl">82.91669</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(sample_Q1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12641</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(sample_Q2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12640</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(sample_Q3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12641</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(sample_Q4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12641</code></pre>
</div>
</div>
</section>
<section id="plotting-slope-stratified-datasets" class="level3">
<h3 class="anchored" data-anchor-id="plotting-slope-stratified-datasets">3.3 Plotting Slope-Stratified Datasets</h3>
<p>To understand the distribution of slope angle in each sample - <strong><code>sample_Q1</code></strong>, <strong><code>sample_Q2</code></strong>, <strong><code>sample_Q3</code></strong>, and <strong><code>sample_Q4</code></strong>, we will plot four histograms as below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>sample_Q1, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">Slope_Angle</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#e9531e"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slopesampling_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>sample_Q2, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">Slope_Angle</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#e9531e"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slopesampling_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>sample_Q3, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">Slope_Angle</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#e9531e"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slopesampling_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>sample_Q4, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">Slope_Angle</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#e9531e"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slopesampling_files/figure-html/unnamed-chunk-5-4.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="creating-correlation-matrix" class="level3">
<h3 class="anchored" data-anchor-id="creating-correlation-matrix">3.4 Creating Correlation Matrix</h3>
<p>Next, we will use the <strong><code>ggcorrmat</code></strong> function from the <strong><code>ggstatsplot</code></strong> package to create a correlation matrix for each dataset.</p>
<ul>
<li><p>We set <strong><code>matrix.type</code></strong> to "upper", which means it will only show the upper triangle of the correlation matrix.</p></li>
<li><p>We set <strong><code>type</code></strong> to "parametric", which means it will calculating the correlations using a parametric method (Pearson's correlation).</p></li>
<li><p>We set <strong><code>k</code></strong> to 2, <strong><code>sig.level</code></strong> to 0.05, <strong><code>conf.level</code></strong> to 0.95, and <strong><code>bf.prior</code></strong> to 0.707. These are parameters for the statistical tests that <strong><code>ggcorrmat</code></strong> performs</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorrmat</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> sample_Q3[, <span class="dv">6</span><span class="sc">:</span><span class="dv">29</span>],  </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">matrix.type =</span> <span class="st">"upper"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"parametric"</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">tr =</span> <span class="fl">0.2</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">partial =</span> <span class="cn">FALSE</span>,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">k =</span> 2L,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">bf.prior =</span> <span class="fl">0.707</span>,</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">ggcorrplot.args =</span> <span class="fu">list</span>(</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">tl.cex =</span> <span class="dv">10</span>,</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch.cex =</span> <span class="dv">5</span>,</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">lab_size =</span> <span class="dv">3</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span> </span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">theme</span>(</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> ggplot2<span class="sc">::</span><span class="fu">element_text</span>(</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">margin =</span> ggplot2<span class="sc">::</span><span class="fu">margin</span>(<span class="at">t =</span> <span class="fl">0.15</span>, <span class="at">r =</span> <span class="fl">0.15</span>, <span class="at">b =</span> <span class="fl">0.15</span>, <span class="at">l =</span> <span class="fl">0.15</span>, <span class="at">unit =</span> <span class="st">"cm"</span>)</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Screenshot 2024-02-19 at 3.12.02 PM.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Q1</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Screenshot 2024-02-19 at 3.13.20 PM.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Q2</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Screenshot 2024-02-19 at 3.15.40 PM.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Q3</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Screenshot 2024-02-19 at 3.10.01 PM.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Q4</figcaption>
</figure>
</div>
</section>
</section>
<section id="logistic-regression-modelling" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression-modelling">4.0 Logistic Regression Modelling</h2>
<p>In this section, we will model a logistic regression model for each data sample.</p>
<p>Before wee build the model, we will need to split each data sample into training data and testing data. This is a common practice in machine learning and statistical modeling, where a model is trained on the training set and then evaluated on the test set. We use <code>sample</code> function to carry out test-train split with 7:3 ratio, resulting in four training sets (<strong><code>Q1_train</code></strong>, <strong><code>Q2_train</code></strong>, <strong><code>Q3_train</code></strong>, <strong><code>Q4_train</code></strong>) and four test sets (<strong><code>Q1_test</code></strong>, <strong><code>Q2_test</code></strong>, <strong><code>Q3_test</code></strong>, <strong><code>Q4_test</code></strong>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>), <span class="fu">nrow</span>(sample_Q1), <span class="at">replace=</span><span class="cn">TRUE</span>, <span class="at">prob=</span><span class="fu">c</span>(<span class="fl">0.70</span>,<span class="fl">0.30</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>Q1_train  <span class="ot">&lt;-</span> sample_Q1[sample, ]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>Q1_test   <span class="ot">&lt;-</span> sample_Q1[<span class="sc">!</span>sample, ]</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>), <span class="fu">nrow</span>(sample_Q2), <span class="at">replace=</span><span class="cn">TRUE</span>, <span class="at">prob=</span><span class="fu">c</span>(<span class="fl">0.70</span>,<span class="fl">0.30</span>))</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>Q2_train  <span class="ot">&lt;-</span> sample_Q2[sample, ]</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>Q2_test   <span class="ot">&lt;-</span> sample_Q2[<span class="sc">!</span>sample, ]</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>), <span class="fu">nrow</span>(sample_Q3), <span class="at">replace=</span><span class="cn">TRUE</span>, <span class="at">prob=</span><span class="fu">c</span>(<span class="fl">0.70</span>,<span class="fl">0.30</span>))</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>Q3_train  <span class="ot">&lt;-</span> sample_Q3[sample, ]</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>Q3_test   <span class="ot">&lt;-</span> sample_Q3[<span class="sc">!</span>sample, ]</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>), <span class="fu">nrow</span>(sample_Q4), <span class="at">replace=</span><span class="cn">TRUE</span>, <span class="at">prob=</span><span class="fu">c</span>(<span class="fl">0.70</span>,<span class="fl">0.30</span>))</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>Q4_train  <span class="ot">&lt;-</span> sample_Q4[sample, ]</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>Q4_test   <span class="ot">&lt;-</span> sample_Q4[<span class="sc">!</span>sample, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once we have split the test and train for each data sample, we will now proceed to build a Logistic Regression (LR) model for each sampling dataset. We will fit the model using the <strong><code>glm</code></strong> function from <strong>stats</strong> package. It is used to fit generalized linear models, specified by giving a symbolic description of the linear predictor and a description of the error distribution.</p>
<section id="logistic-regression-model-1-slope-cut-off-1st-quartile" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression-model-1-slope-cut-off-1st-quartile">4.1 Logistic Regression Model 1 (Slope Cut-off = 1st Quartile)</h3>
<p>First LR model, <code>log_model_1</code> is fitted using <code>Q1_train</code> dataset with specifications as follows:</p>
<ul>
<li><p>The model is predicting the <strong><code>Landslide</code></strong> variable based on a number of predictor variables, including <strong><code>Elevation</code></strong>, <strong><code>Slope_Angle</code></strong>, <strong><code>Aspect_North</code></strong>, <strong><code>Aspect_NorthEast</code></strong>, <strong><code>Aspect_East</code></strong>, <strong><code>Aspect_SouthEast</code></strong>, <strong><code>Aspect_South</code></strong>, <strong><code>Aspect_SouthWest</code></strong>, <strong><code>Aspect_West</code></strong>, <strong><code>Profile_Curvature</code></strong>, <strong><code>Plan_Curvature</code></strong>, <strong><code>Lithology_Metamorphic</code></strong>, <strong><code>Lithology_Sedimentary</code></strong>, <strong><code>Lithology_Plutonic</code></strong>, <strong><code>Lithology_Unconsolidated</code></strong>, <strong><code>Proximity_Settlement</code></strong>, <strong><code>Proximity_Stream</code></strong>, <strong><code>Proximity_Road</code></strong>, <strong><code>Proximity_Fault</code></strong>, <strong><code>Landuse_Vegetation</code></strong>, <strong><code>Precipitation</code></strong>, <strong><code>TWI</code></strong>, <strong><code>SPI</code></strong>, and <strong><code>STI</code></strong>.</p></li>
<li><p>The <strong><code>family</code></strong> argument is set to <strong><code>"binomial"</code></strong> to fit a binomial logistic regression model.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>log_model_1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Landslide <span class="sc">~</span> Elevation <span class="sc">+</span> Slope_Angle <span class="sc">+</span> Aspect_North <span class="sc">+</span> Aspect_NorthEast <span class="sc">+</span> Aspect_East<span class="sc">+</span>Aspect_SouthEast<span class="sc">+</span>Aspect_South <span class="sc">+</span> Aspect_SouthWest <span class="sc">+</span>Aspect_West <span class="sc">+</span> Profile_Curvature <span class="sc">+</span>Plan_Curvature <span class="sc">+</span> Lithology_Metamorphic<span class="sc">+</span>Lithology_Sedimentary <span class="sc">+</span> Lithology_Plutonic<span class="sc">+</span>Lithology_Unconsolidated <span class="sc">+</span> Proximity_Settlement<span class="sc">+</span>Proximity_Stream<span class="sc">+</span>Proximity_Road<span class="sc">+</span>Proximity_Fault<span class="sc">+</span>Landuse_Vegetation<span class="sc">+</span>Precipitation<span class="sc">+</span>TWI<span class="sc">+</span>SPI<span class="sc">+</span>STI, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> Q1_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="generating-model-summary" class="level4">
<h4 class="anchored" data-anchor-id="generating-model-summary">4.1.1 Generating Model Summary</h4>
<p>Once we have fitted the model, we will generate a summary of the model using <code>summary()</code> function. The model summary give us useful information about the model, including the coefficients of the predictor variables, the standard errors of these coefficients, and the statistical significance of each predictor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_model_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Landslide ~ Elevation + Slope_Angle + Aspect_North + 
    Aspect_NorthEast + Aspect_East + Aspect_SouthEast + Aspect_South + 
    Aspect_SouthWest + Aspect_West + Profile_Curvature + Plan_Curvature + 
    Lithology_Metamorphic + Lithology_Sedimentary + Lithology_Plutonic + 
    Lithology_Unconsolidated + Proximity_Settlement + Proximity_Stream + 
    Proximity_Road + Proximity_Fault + Landuse_Vegetation + Precipitation + 
    TWI + SPI + STI, family = "binomial", data = Q1_train)

Coefficients:
                           Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)              -2.794e+00  3.113e-01  -8.974  &lt; 2e-16 ***
Elevation                -1.724e-04  5.647e-05  -3.054 0.002258 ** 
Slope_Angle               2.597e-01  6.740e-03  38.535  &lt; 2e-16 ***
Aspect_North             -9.356e-02  1.477e-01  -0.634 0.526365    
Aspect_NorthEast         -2.392e-01  1.249e-01  -1.915 0.055459 .  
Aspect_East              -4.514e-01  1.233e-01  -3.662 0.000250 ***
Aspect_SouthEast         -4.341e-01  1.191e-01  -3.644 0.000269 ***
Aspect_South             -3.122e-01  1.143e-01  -2.731 0.006320 ** 
Aspect_SouthWest         -2.871e-01  1.169e-01  -2.456 0.014032 *  
Aspect_West              -2.082e-01  1.178e-01  -1.767 0.077152 .  
Profile_Curvature        -9.067e+02  3.439e+01 -26.364  &lt; 2e-16 ***
Plan_Curvature           -7.961e+02  4.136e+01 -19.249  &lt; 2e-16 ***
Lithology_Metamorphic     5.804e-01  1.727e-01   3.361 0.000777 ***
Lithology_Sedimentary     1.167e+00  1.789e-01   6.522 6.93e-11 ***
Lithology_Plutonic       -8.392e-01  1.629e-01  -5.153 2.57e-07 ***
Lithology_Unconsolidated  1.236e+00  1.732e-01   7.140 9.34e-13 ***
Proximity_Settlement      6.778e-05  5.184e-05   1.307 0.191050    
Proximity_Stream         -8.153e-03  2.746e-03  -2.970 0.002982 ** 
Proximity_Road           -4.688e-03  1.830e-03  -2.561 0.010429 *  
Proximity_Fault          -1.307e-05  3.156e-05  -0.414 0.678729    
Landuse_Vegetation        5.620e-01  6.669e-02   8.427  &lt; 2e-16 ***
Precipitation            -6.706e+00  7.590e-01  -8.836  &lt; 2e-16 ***
TWI                      -4.276e-02  1.386e-02  -3.085 0.002039 ** 
SPI                       1.391e+00  1.179e+00   1.180 0.237822    
STI                      -7.053e-04  1.362e-03  -0.518 0.604584    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 11873.9  on 8810  degrees of freedom
Residual deviance:  7057.4  on 8786  degrees of freedom
AIC: 7107.4

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
</section>
<section id="calculating-percentage-of-deviance" class="level4">
<h4 class="anchored" data-anchor-id="calculating-percentage-of-deviance">4.1.2 Calculating Percentage of Deviance</h4>
<p>Next, we will calculate the percentage of deviance explained by the model. The deviance is a measure of how well the model fits the data, with lower values indicating a better fit. The null deviance is the deviance of a model with no predictors, i.e., a model that only includes the intercept. So, this calculation gives me the percentage reduction in deviance when going from the null model to the current model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span><span class="fu">with</span>(<span class="fu">summary</span>(log_model_1), <span class="dv">1</span> <span class="sc">-</span> deviance<span class="sc">/</span>null.deviance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40.56421</code></pre>
</div>
</div>
</section>
<section id="confusion-matrix" class="level4">
<h4 class="anchored" data-anchor-id="confusion-matrix">4.1.3 Confusion Matrix</h4>
<p>Next, we will generate a confusion matrix for the model predictions using <code>blr_confusion_matrix()</code> function from <code>blorr</code> package. The confusion matrix shows the number of true positives, true negatives, false positives, and false negatives. The <strong><code>cutoff</code></strong> argument is set to 0.5, which means that predicted probabilities greater than or equal to 0.5 are classified as positive, and predicted probabilities less than 0.5 are classified as negative.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">blr_confusion_matrix</span>(log_model_1, <span class="at">cutoff =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics 

          Reference
Prediction    0    1
         0 4606  878
         1  663 2664

                Accuracy : 0.8251 
     No Information Rate : 0.5980 

                   Kappa : 0.6326 

McNemars's Test P-Value  : 0.0000 

             Sensitivity : 0.7521 
             Specificity : 0.8742 
          Pos Pred Value : 0.8007 
          Neg Pred Value : 0.8399 
              Prevalence : 0.4020 
          Detection Rate : 0.3023 
    Detection Prevalence : 0.3776 
       Balanced Accuracy : 0.8131 
               Precision : 0.8007 
                  Recall : 0.7521 

        'Positive' Class : 1</code></pre>
</div>
</div>
</section>
<section id="ploting-roc-curve-and-calculating-auc" class="level4">
<h4 class="anchored" data-anchor-id="ploting-roc-curve-and-calculating-auc">4.1.4 Ploting ROC Curve and Calculating AUC</h4>
<p>Finally, we will plot the ROC curve and calculate the AUC. The ROC curve is a plot of the true positive rate against the false positive rate for different cutoff values, and the AUC is the area under the ROC curve. These are common metrics for evaluating the performance of a binary classifier. The <strong><code>roc</code></strong> function from the <strong><code>pROC</code></strong> package is used to calculate the ROC curve, and the <strong><code>auc</code></strong> function is used to calculate the AUC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(log_model_1, Q1_test[, <span class="dv">6</span><span class="sc">:</span><span class="dv">29</span>], <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>roc_curve <span class="ot">&lt;-</span> <span class="fu">roc</span>(Q1_test<span class="sc">$</span>Landslide, predicted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc_curve, <span class="at">main =</span> <span class="st">"ROC Curve (Model 1)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slopesampling_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>auc_value <span class="ot">&lt;-</span> <span class="fu">auc</span>(roc_curve)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AUC:"</span>, auc_value, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>AUC: 0.8863659 </code></pre>
</div>
</div>
</section>
</section>
<section id="logistic-regression-model-2-slope-cut-off-2nd-quartile" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression-model-2-slope-cut-off-2nd-quartile">4.2 Logistic Regression Model 2 (Slope Cut-off = 2nd Quartile)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>log_model_2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Landslide <span class="sc">~</span> Elevation <span class="sc">+</span> Slope_Angle <span class="sc">+</span> Aspect_North <span class="sc">+</span> Aspect_NorthEast <span class="sc">+</span> Aspect_East<span class="sc">+</span>Aspect_SouthEast<span class="sc">+</span>Aspect_South <span class="sc">+</span> Aspect_SouthWest <span class="sc">+</span>Aspect_West <span class="sc">+</span> Profile_Curvature <span class="sc">+</span>Plan_Curvature <span class="sc">+</span> Lithology_Metamorphic<span class="sc">+</span>Lithology_Sedimentary <span class="sc">+</span> Lithology_Plutonic<span class="sc">+</span>Lithology_Unconsolidated <span class="sc">+</span> Proximity_Settlement<span class="sc">+</span>Proximity_Stream<span class="sc">+</span>Proximity_Road<span class="sc">+</span>Proximity_Fault<span class="sc">+</span>Landuse_Vegetation<span class="sc">+</span>Precipitation<span class="sc">+</span>TWI<span class="sc">+</span>SPI<span class="sc">+</span>STI, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> Q2_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="generating-model-summary-1" class="level4">
<h4 class="anchored" data-anchor-id="generating-model-summary-1">4.2.1 Generating Model Summary</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_model_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Landslide ~ Elevation + Slope_Angle + Aspect_North + 
    Aspect_NorthEast + Aspect_East + Aspect_SouthEast + Aspect_South + 
    Aspect_SouthWest + Aspect_West + Profile_Curvature + Plan_Curvature + 
    Lithology_Metamorphic + Lithology_Sedimentary + Lithology_Plutonic + 
    Lithology_Unconsolidated + Proximity_Settlement + Proximity_Stream + 
    Proximity_Road + Proximity_Fault + Landuse_Vegetation + Precipitation + 
    TWI + SPI + STI, family = "binomial", data = Q2_train)

Coefficients:
                           Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)              -9.793e+00  8.992e-01 -10.890  &lt; 2e-16 ***
Elevation                -3.272e-04  1.487e-04  -2.201  0.02777 *  
Slope_Angle               5.333e-01  2.321e-02  22.984  &lt; 2e-16 ***
Aspect_North             -2.164e-01  2.608e-01  -0.830  0.40667    
Aspect_NorthEast         -3.765e-01  2.183e-01  -1.725  0.08456 .  
Aspect_East              -2.053e-01  2.216e-01  -0.927  0.35412    
Aspect_SouthEast         -2.621e-01  2.177e-01  -1.204  0.22861    
Aspect_South             -1.336e-01  2.235e-01  -0.598  0.55009    
Aspect_SouthWest          4.924e-01  2.474e-01   1.991  0.04653 *  
Aspect_West               1.508e-01  2.373e-01   0.635  0.52518    
Profile_Curvature        -7.349e+02  6.238e+01 -11.782  &lt; 2e-16 ***
Plan_Curvature           -5.507e+02  7.033e+01  -7.831 4.84e-15 ***
Lithology_Metamorphic     7.038e-01  2.537e-01   2.775  0.00553 ** 
Lithology_Sedimentary     1.333e+00  2.760e-01   4.831 1.36e-06 ***
Lithology_Plutonic       -4.923e-01  2.603e-01  -1.891  0.05857 .  
Lithology_Unconsolidated  1.359e+00  2.636e-01   5.155 2.53e-07 ***
Proximity_Settlement      1.139e-04  9.063e-05   1.256  0.20895    
Proximity_Stream         -5.105e-03  4.901e-03  -1.042  0.29755    
Proximity_Road           -1.287e-03  3.258e-03  -0.395  0.69287    
Proximity_Fault           8.893e-05  5.089e-05   1.747  0.08057 .  
Landuse_Vegetation        7.225e-01  1.430e-01   5.053 4.36e-07 ***
Precipitation            -2.029e+00  1.302e+00  -1.558  0.11917    
TWI                      -2.203e-02  5.335e-02  -0.413  0.67969    
SPI                       3.578e-01  1.861e+00   0.192  0.84750    
STI                      -3.051e-03  2.059e-03  -1.482  0.13842    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 4177.4  on 8824  degrees of freedom
Residual deviance: 2413.0  on 8800  degrees of freedom
AIC: 2463

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
</section>
<section id="calculating-percentage-of-deviance-1" class="level4">
<h4 class="anchored" data-anchor-id="calculating-percentage-of-deviance-1">4.2.2 Calculating Percentage of Deviance</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span><span class="fu">with</span>(<span class="fu">summary</span>(log_model_2), <span class="dv">1</span> <span class="sc">-</span> deviance<span class="sc">/</span>null.deviance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 42.23566</code></pre>
</div>
</div>
</section>
<section id="confusion-matrix-1" class="level4">
<h4 class="anchored" data-anchor-id="confusion-matrix-1">4.2.3 Confusion Matrix</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">blr_confusion_matrix</span>(log_model_2, <span class="at">cutoff =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics 

          Reference
Prediction    0    1
         0  192   90
         1  369 8174

                Accuracy : 0.9480 
     No Information Rate : 0.0636 

                   Kappa : 0.4313 

McNemars's Test P-Value  : 0.0000 

             Sensitivity : 0.9891 
             Specificity : 0.3422 
          Pos Pred Value : 0.9568 
          Neg Pred Value : 0.6809 
              Prevalence : 0.9364 
          Detection Rate : 0.9262 
    Detection Prevalence : 0.9680 
       Balanced Accuracy : 0.6657 
               Precision : 0.9568 
                  Recall : 0.9891 

        'Positive' Class : 1</code></pre>
</div>
</div>
</section>
<section id="ploting-roc-curve-and-calculating-auc-1" class="level4">
<h4 class="anchored" data-anchor-id="ploting-roc-curve-and-calculating-auc-1">4.2.4 Ploting ROC Curve and Calculating AUC</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(log_model_2, Q2_test[, <span class="dv">6</span><span class="sc">:</span><span class="dv">29</span>], <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>roc_curve <span class="ot">&lt;-</span> <span class="fu">roc</span>(Q2_test<span class="sc">$</span>Landslide, predicted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the ROC curve</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc_curve, <span class="at">main =</span> <span class="st">"ROC Curve (Model 2)"</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray"</span>)  <span class="co"># Add a reference line for a random classifier</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slopesampling_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>auc_value <span class="ot">&lt;-</span> <span class="fu">auc</span>(roc_curve)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AUC:"</span>, auc_value, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>AUC: 0.9254063 </code></pre>
</div>
</div>
</section>
</section>
<section id="logistic-regression-model-3-slope-cut-off-3rd-quartile" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression-model-3-slope-cut-off-3rd-quartile">4.3 Logistic Regression Model 3 (Slope Cut-off = 3rd Quartile)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>log_model_3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Landslide <span class="sc">~</span> Elevation <span class="sc">+</span> Aspect_North <span class="sc">+</span> Aspect_NorthEast <span class="sc">+</span> Aspect_East<span class="sc">+</span>Aspect_SouthEast<span class="sc">+</span>Aspect_South <span class="sc">+</span> Aspect_SouthWest <span class="sc">+</span>Aspect_West <span class="sc">+</span> Profile_Curvature <span class="sc">+</span>Plan_Curvature <span class="sc">+</span> Lithology_Metamorphic<span class="sc">+</span>Lithology_Sedimentary <span class="sc">+</span> Lithology_Plutonic<span class="sc">+</span>Lithology_Unconsolidated <span class="sc">+</span> Proximity_Settlement<span class="sc">+</span>Proximity_Stream<span class="sc">+</span>Proximity_Road<span class="sc">+</span>Proximity_Fault<span class="sc">+</span>Landuse_Vegetation<span class="sc">+</span>Precipitation<span class="sc">+</span>TWI<span class="sc">+</span>SPI<span class="sc">+</span>STI, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> Q3_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
</div>
</div>
<section id="generating-model-summary-2" class="level4">
<h4 class="anchored" data-anchor-id="generating-model-summary-2">4.3.1 Generating Model Summary</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_model_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Landslide ~ Elevation + Aspect_North + Aspect_NorthEast + 
    Aspect_East + Aspect_SouthEast + Aspect_South + Aspect_SouthWest + 
    Aspect_West + Profile_Curvature + Plan_Curvature + Lithology_Metamorphic + 
    Lithology_Sedimentary + Lithology_Plutonic + Lithology_Unconsolidated + 
    Proximity_Settlement + Proximity_Stream + Proximity_Road + 
    Proximity_Fault + Landuse_Vegetation + Precipitation + TWI + 
    SPI + STI, family = "binomial", data = Q3_train)

Coefficients:
                           Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)               3.596e+01  2.468e+04   0.001   0.9988  
Elevation                 2.287e-04  8.979e-04   0.255   0.7990  
Aspect_North             -4.609e-01  1.442e+00  -0.320   0.7493  
Aspect_NorthEast         -8.754e-01  1.191e+00  -0.735   0.4623  
Aspect_East               4.314e-01  1.464e+00   0.295   0.7682  
Aspect_SouthEast          6.442e-01  1.446e+00   0.445   0.6561  
Aspect_South             -4.903e-02  1.273e+00  -0.039   0.9693  
Aspect_SouthWest          5.415e-02  1.264e+00   0.043   0.9658  
Aspect_West               1.655e+01  2.012e+03   0.008   0.9934  
Profile_Curvature        -4.432e+02  2.712e+02  -1.634   0.1022  
Plan_Curvature           -6.625e+02  2.935e+02  -2.257   0.0240 *
Lithology_Metamorphic    -2.924e+01  2.468e+04  -0.001   0.9991  
Lithology_Sedimentary    -2.753e+01  2.468e+04  -0.001   0.9991  
Lithology_Plutonic       -3.002e+01  2.468e+04  -0.001   0.9990  
Lithology_Unconsolidated -1.236e+01  2.472e+04   0.000   0.9996  
Proximity_Settlement      7.875e-04  6.524e-04   1.207   0.2274  
Proximity_Stream         -2.957e-02  3.274e-02  -0.903   0.3664  
Proximity_Road           -5.091e-04  1.914e-02  -0.027   0.9788  
Proximity_Fault           8.574e-06  2.786e-04   0.031   0.9754  
Landuse_Vegetation        1.410e+00  9.620e-01   1.465   0.1428  
Precipitation             6.687e-01  8.479e+00   0.079   0.9371  
TWI                      -3.150e-01  2.966e-01  -1.062   0.2883  
SPI                      -1.596e+01  7.151e+00  -2.232   0.0256 *
STI                       1.314e-01  9.722e-02   1.351   0.1766  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 182.70  on 8938  degrees of freedom
Residual deviance: 133.76  on 8915  degrees of freedom
AIC: 181.76

Number of Fisher Scoring iterations: 22</code></pre>
</div>
</div>
</section>
<section id="calculating-percentage-of-deviance-2" class="level4">
<h4 class="anchored" data-anchor-id="calculating-percentage-of-deviance-2">4.3.2 Calculating Percentage of Deviance</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span><span class="fu">with</span>(<span class="fu">summary</span>(log_model_3), <span class="dv">1</span> <span class="sc">-</span> deviance<span class="sc">/</span>null.deviance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 26.78832</code></pre>
</div>
</div>
</section>
<section id="confusion-matrix-2" class="level4">
<h4 class="anchored" data-anchor-id="confusion-matrix-2">4.3.3 Confusion Matrix</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">blr_confusion_matrix</span>(log_model_3, <span class="at">cutoff =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics 

          Reference
Prediction    0    1
         0    1    0
         1   11 8927

                Accuracy : 0.9988 
     No Information Rate : 0.0013 

                   Kappa : 0.1537 

McNemars's Test P-Value  : 0.0026 

             Sensitivity : 1.0000 
             Specificity : 0.0833 
          Pos Pred Value : 0.9988 
          Neg Pred Value : 1.0000 
              Prevalence : 0.9987 
          Detection Rate : 0.9987 
    Detection Prevalence : 0.9999 
       Balanced Accuracy : 0.5417 
               Precision : 0.9988 
                  Recall : 1.0000 

        'Positive' Class : 1</code></pre>
</div>
</div>
</section>
<section id="ploting-roc-curve-and-calculating-auc-2" class="level4">
<h4 class="anchored" data-anchor-id="ploting-roc-curve-and-calculating-auc-2">4.3.4 Ploting ROC Curve and Calculating AUC</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(log_model_3, Q3_test[, <span class="dv">6</span><span class="sc">:</span><span class="dv">29</span>], <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>roc_curve <span class="ot">&lt;-</span> <span class="fu">roc</span>(Q3_test<span class="sc">$</span>Landslide, predicted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the ROC curve</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc_curve, <span class="at">main =</span> <span class="st">"ROC Curve (Model 3)"</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slopesampling_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>auc_value <span class="ot">&lt;-</span> <span class="fu">auc</span>(roc_curve)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AUC:"</span>, auc_value, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>AUC: 0.776792 </code></pre>
</div>
</div>
</section>
</section>
<section id="logistic-regression-model-4-slope-cut-off-4th-quartile" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression-model-4-slope-cut-off-4th-quartile">4.4 Logistic Regression Model 4 (Slope Cut-off = 4th Quartile)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>log_model_4 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Landslide <span class="sc">~</span> Elevation <span class="sc">+</span> Slope_Angle <span class="sc">+</span> Aspect_North <span class="sc">+</span> Aspect_NorthEast <span class="sc">+</span> Aspect_East<span class="sc">+</span>Aspect_SouthEast<span class="sc">+</span>Aspect_South <span class="sc">+</span> Aspect_SouthWest <span class="sc">+</span>Aspect_West <span class="sc">+</span> Profile_Curvature <span class="sc">+</span>Plan_Curvature <span class="sc">+</span> Lithology_Metamorphic<span class="sc">+</span>Lithology_Sedimentary <span class="sc">+</span> Lithology_Plutonic<span class="sc">+</span>Lithology_Unconsolidated <span class="sc">+</span> Proximity_Settlement<span class="sc">+</span>Proximity_Stream<span class="sc">+</span>Proximity_Road<span class="sc">+</span>Proximity_Fault<span class="sc">+</span>Landuse_Vegetation<span class="sc">+</span>Precipitation<span class="sc">+</span>TWI<span class="sc">+</span>SPI<span class="sc">+</span>STI, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> Q4_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="generating-model-summary-3" class="level4">
<h4 class="anchored" data-anchor-id="generating-model-summary-3">4.4.1 Generating Model Summary</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_model_4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Landslide ~ Elevation + Slope_Angle + Aspect_North + 
    Aspect_NorthEast + Aspect_East + Aspect_SouthEast + Aspect_South + 
    Aspect_SouthWest + Aspect_West + Profile_Curvature + Plan_Curvature + 
    Lithology_Metamorphic + Lithology_Sedimentary + Lithology_Plutonic + 
    Lithology_Unconsolidated + Proximity_Settlement + Proximity_Stream + 
    Proximity_Road + Proximity_Fault + Landuse_Vegetation + Precipitation + 
    TWI + SPI + STI, family = "binomial", data = Q4_train)

Coefficients:
                           Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)               1.702e+01  2.042e+00   8.333  &lt; 2e-16 ***
Elevation                 7.170e-04  2.959e-04   2.423 0.015382 *  
Slope_Angle              -3.218e-01  1.862e-02 -17.286  &lt; 2e-16 ***
Aspect_North              2.092e-01  6.855e-01   0.305 0.760250    
Aspect_NorthEast         -1.189e-02  6.083e-01  -0.020 0.984411    
Aspect_East               6.784e-01  6.150e-01   1.103 0.270014    
Aspect_SouthEast          5.039e-02  5.732e-01   0.088 0.929956    
Aspect_South              5.294e-01  5.671e-01   0.934 0.350520    
Aspect_SouthWest         -8.593e-02  5.746e-01  -0.150 0.881119    
Aspect_West               3.040e-01  6.282e-01   0.484 0.628406    
Profile_Curvature        -1.228e+02  7.900e+01  -1.555 0.119931    
Plan_Curvature           -6.581e+01  1.054e+02  -0.624 0.532510    
Lithology_Metamorphic     2.681e+00  6.517e-01   4.114 3.89e-05 ***
Lithology_Sedimentary     3.183e+00  6.958e-01   4.574 4.78e-06 ***
Lithology_Plutonic        3.076e+00  6.224e-01   4.942 7.73e-07 ***
Lithology_Unconsolidated  2.776e+00  7.836e-01   3.543 0.000396 ***
Proximity_Settlement     -5.615e-04  1.926e-04  -2.915 0.003558 ** 
Proximity_Stream         -2.983e-02  1.558e-02  -1.915 0.055457 .  
Proximity_Road            1.682e-02  6.434e-03   2.614 0.008949 ** 
Proximity_Fault          -2.671e-04  8.868e-05  -3.012 0.002599 ** 
Landuse_Vegetation        1.036e+00  3.209e-01   3.228 0.001248 ** 
Precipitation            -1.339e+00  4.040e+00  -0.331 0.740381    
TWI                       3.670e-01  1.565e-01   2.345 0.019005 *  
SPI                       3.964e+00  9.246e+00   0.429 0.668146    
STI                      -4.607e-03  4.049e-03  -1.138 0.255210    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2383.3  on 8765  degrees of freedom
Residual deviance:  534.1  on 8741  degrees of freedom
AIC: 584.1

Number of Fisher Scoring iterations: 10</code></pre>
</div>
</div>
</section>
<section id="calculating-percentage-of-deviance-3" class="level4">
<h4 class="anchored" data-anchor-id="calculating-percentage-of-deviance-3">4.4.2 Calculating Percentage of Deviance</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span><span class="fu">with</span>(<span class="fu">summary</span>(log_model_4), <span class="dv">1</span> <span class="sc">-</span> deviance<span class="sc">/</span>null.deviance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 77.58965</code></pre>
</div>
</div>
</section>
<section id="confusion-matrix-3" class="level4">
<h4 class="anchored" data-anchor-id="confusion-matrix-3">4.4.3 Confusion Matrix</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">blr_confusion_matrix</span>(log_model_4, <span class="at">cutoff =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics 

          Reference
Prediction    0    1
         0  214   35
         1   52 8465

                Accuracy : 0.9901 
     No Information Rate : 0.0303 

                   Kappa : 0.8260 

McNemars's Test P-Value  : 0.0863 

             Sensitivity : 0.9959 
             Specificity : 0.8045 
          Pos Pred Value : 0.9939 
          Neg Pred Value : 0.8594 
              Prevalence : 0.9697 
          Detection Rate : 0.9657 
    Detection Prevalence : 0.9716 
       Balanced Accuracy : 0.9002 
               Precision : 0.9939 
                  Recall : 0.9959 

        'Positive' Class : 1</code></pre>
</div>
</div>
</section>
<section id="ploting-roc-curve-and-calculating-auc-3" class="level4">
<h4 class="anchored" data-anchor-id="ploting-roc-curve-and-calculating-auc-3">4.4.4 Ploting ROC Curve and Calculating AUC</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(log_model_4, Q4_test[, <span class="dv">6</span><span class="sc">:</span><span class="dv">29</span>], <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>roc_curve <span class="ot">&lt;-</span> <span class="fu">roc</span>(Q4_test<span class="sc">$</span>Landslide, predicted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc_curve, <span class="at">main =</span> <span class="st">"ROC Curve (Model 4)"</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slopesampling_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>auc_value <span class="ot">&lt;-</span> <span class="fu">auc</span>(roc_curve)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AUC:"</span>, auc_value, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>AUC: 0.9775011 </code></pre>
</div>
</div>
</section>
</section>
<section id="logistic-regression-model-5-slope-cut-off-25" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression-model-5-slope-cut-off-25">4.5 Logistic Regression Model 5 (Slope Cut-off = 25)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>sample_Q5 <span class="ot">&lt;-</span> <span class="fu">subset</span>(train_grids_v4,Slope_Angle <span class="sc">&lt;</span> <span class="dv">25</span>)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(sample_Q5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18578</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>sample_Q5, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">Slope_Angle</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#e9531e"</span>) <span class="sc">+</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Slope Stratified Sampling (Cut-off 25)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slopesampling_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>), <span class="fu">nrow</span>(sample_Q5), <span class="at">replace=</span><span class="cn">TRUE</span>, <span class="at">prob=</span><span class="fu">c</span>(<span class="fl">0.70</span>,<span class="fl">0.30</span>))</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>Q5_train  <span class="ot">&lt;-</span> sample_Q5[sample, ]</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>Q5_test   <span class="ot">&lt;-</span> sample_Q5[<span class="sc">!</span>sample, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>log_model_5 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Landslide <span class="sc">~</span> Elevation <span class="sc">+</span> Slope_Angle <span class="sc">+</span> Aspect_North <span class="sc">+</span> Aspect_NorthEast <span class="sc">+</span> Aspect_East<span class="sc">+</span>Aspect_SouthEast<span class="sc">+</span>Aspect_South <span class="sc">+</span> Aspect_SouthWest <span class="sc">+</span>Aspect_West <span class="sc">+</span> Profile_Curvature <span class="sc">+</span>Plan_Curvature <span class="sc">+</span> Lithology_Metamorphic<span class="sc">+</span>Lithology_Sedimentary <span class="sc">+</span> Lithology_Plutonic<span class="sc">+</span>Lithology_Unconsolidated <span class="sc">+</span> Proximity_Settlement<span class="sc">+</span>Proximity_Stream<span class="sc">+</span>Proximity_Road<span class="sc">+</span>Proximity_Fault<span class="sc">+</span>Landuse_Vegetation<span class="sc">+</span>Precipitation<span class="sc">+</span>TWI<span class="sc">+</span>SPI<span class="sc">+</span>STI, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> Q5_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="generating-model-summary-4" class="level4">
<h4 class="anchored" data-anchor-id="generating-model-summary-4">4.5.1 Generating Model Summary</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_model_5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Landslide ~ Elevation + Slope_Angle + Aspect_North + 
    Aspect_NorthEast + Aspect_East + Aspect_SouthEast + Aspect_South + 
    Aspect_SouthWest + Aspect_West + Profile_Curvature + Plan_Curvature + 
    Lithology_Metamorphic + Lithology_Sedimentary + Lithology_Plutonic + 
    Lithology_Unconsolidated + Proximity_Settlement + Proximity_Stream + 
    Proximity_Road + Proximity_Fault + Landuse_Vegetation + Precipitation + 
    TWI + SPI + STI, family = "binomial", data = Q5_train)

Coefficients:
                           Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)              -3.248e+00  2.773e-01 -11.714  &lt; 2e-16 ***
Elevation                -1.579e-04  5.200e-05  -3.037 0.002393 ** 
Slope_Angle               2.557e-01  4.953e-03  51.621  &lt; 2e-16 ***
Aspect_North             -6.206e-02  1.283e-01  -0.484 0.628586    
Aspect_NorthEast         -2.895e-01  1.104e-01  -2.622 0.008747 ** 
Aspect_East              -2.726e-01  1.083e-01  -2.518 0.011817 *  
Aspect_SouthEast         -4.054e-01  1.056e-01  -3.840 0.000123 ***
Aspect_South             -2.760e-01  1.033e-01  -2.672 0.007548 ** 
Aspect_SouthWest         -1.468e-01  1.054e-01  -1.393 0.163538    
Aspect_West              -3.135e-02  1.066e-01  -0.294 0.768601    
Profile_Curvature        -8.624e+02  3.049e+01 -28.287  &lt; 2e-16 ***
Plan_Curvature           -7.488e+02  3.436e+01 -21.791  &lt; 2e-16 ***
Lithology_Metamorphic     5.632e-01  1.371e-01   4.109 3.98e-05 ***
Lithology_Sedimentary     1.040e+00  1.431e-01   7.269 3.62e-13 ***
Lithology_Plutonic       -6.008e-01  1.299e-01  -4.624 3.76e-06 ***
Lithology_Unconsolidated  1.208e+00  1.386e-01   8.720  &lt; 2e-16 ***
Proximity_Settlement      1.253e-04  4.537e-05   2.761 0.005755 ** 
Proximity_Stream         -6.857e-03  2.435e-03  -2.816 0.004862 ** 
Proximity_Road           -5.513e-03  1.602e-03  -3.442 0.000578 ***
Proximity_Fault           2.778e-06  2.580e-05   0.108 0.914247    
Landuse_Vegetation        6.846e-01  6.044e-02  11.326  &lt; 2e-16 ***
Precipitation            -4.851e+00  6.507e-01  -7.455 9.02e-14 ***
TWI                      -3.561e-02  1.331e-02  -2.675 0.007483 ** 
SPI                       9.955e-01  9.406e-01   1.058 0.289844    
STI                      -9.281e-04  1.144e-03  -0.811 0.417409    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 17851.7  on 12969  degrees of freedom
Residual deviance:  9295.5  on 12945  degrees of freedom
AIC: 9345.5

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
</section>
<section id="calculating-percentage-of-deviance-4" class="level4">
<h4 class="anchored" data-anchor-id="calculating-percentage-of-deviance-4">4.5.2 Calculating Percentage of Deviance</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span><span class="fu">with</span>(<span class="fu">summary</span>(log_model_5), <span class="dv">1</span> <span class="sc">-</span> deviance<span class="sc">/</span>null.deviance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 47.92954</code></pre>
</div>
</div>
</section>
<section id="confusion-matrix-4" class="level4">
<h4 class="anchored" data-anchor-id="confusion-matrix-4">4.5.3 Confusion Matrix</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">blr_confusion_matrix</span>(log_model_5, <span class="at">cutoff =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics 

          Reference
Prediction    0    1
         0 4809 1007
         1 1031 6123

                Accuracy : 0.8429 
     No Information Rate : 0.4503 

                   Kappa : 0.6825 

McNemars's Test P-Value  : 0.6104 

             Sensitivity : 0.8588 
             Specificity : 0.8235 
          Pos Pred Value : 0.8559 
          Neg Pred Value : 0.8269 
              Prevalence : 0.5497 
          Detection Rate : 0.4721 
    Detection Prevalence : 0.5516 
       Balanced Accuracy : 0.8411 
               Precision : 0.8559 
                  Recall : 0.8588 

        'Positive' Class : 1</code></pre>
</div>
</div>
</section>
<section id="ploting-roc-curve-and-calculating-auc-4" class="level4">
<h4 class="anchored" data-anchor-id="ploting-roc-curve-and-calculating-auc-4">4.5.4 Ploting ROC Curve and Calculating AUC</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(log_model_5, Q5_test[, <span class="dv">6</span><span class="sc">:</span><span class="dv">29</span>], <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>roc_curve <span class="ot">&lt;-</span> <span class="fu">roc</span>(Q5_test<span class="sc">$</span>Landslide, predicted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the ROC curve</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc_curve, <span class="at">main =</span> <span class="st">"ROC Curve (Model 5)"</span>)</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray"</span>)  <span class="co"># Add a reference line for a random classifier</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slopesampling_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>auc_value <span class="ot">&lt;-</span> <span class="fu">auc</span>(roc_curve)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AUC:"</span>, auc_value, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>AUC: 0.9180697 </code></pre>
</div>
</div>
</section>
</section>
<section id="logistic-regression-model-6-slope-cut-off-20" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression-model-6-slope-cut-off-20">4.6 Logistic Regression Model 6 (Slope Cut-off = 20)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>sample_Q6 <span class="ot">&lt;-</span> <span class="fu">subset</span>(train_grids_v4,Slope_Angle <span class="sc">&lt;</span> <span class="dv">20</span>)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(sample_Q6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14020</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>sample_Q6, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">Slope_Angle</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#e9531e"</span>)<span class="sc">+</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Slope Stratified Sampling (Cut-off 20)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slopesampling_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>), <span class="fu">nrow</span>(sample_Q6), <span class="at">replace=</span><span class="cn">TRUE</span>, <span class="at">prob=</span><span class="fu">c</span>(<span class="fl">0.70</span>,<span class="fl">0.30</span>))</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>Q6_train  <span class="ot">&lt;-</span> sample_Q6[sample, ]</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>Q6_test   <span class="ot">&lt;-</span> sample_Q6[<span class="sc">!</span>sample, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>log_model_6 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Landslide <span class="sc">~</span> Elevation <span class="sc">+</span> Slope_Angle <span class="sc">+</span> Aspect_North <span class="sc">+</span> Aspect_NorthEast <span class="sc">+</span> Aspect_East<span class="sc">+</span>Aspect_SouthEast<span class="sc">+</span>Aspect_South <span class="sc">+</span> Aspect_SouthWest <span class="sc">+</span>Aspect_West <span class="sc">+</span> Profile_Curvature <span class="sc">+</span>Plan_Curvature <span class="sc">+</span> Lithology_Metamorphic<span class="sc">+</span>Lithology_Sedimentary <span class="sc">+</span> Lithology_Plutonic<span class="sc">+</span>Lithology_Unconsolidated <span class="sc">+</span> Proximity_Settlement<span class="sc">+</span>Proximity_Stream<span class="sc">+</span>Proximity_Road<span class="sc">+</span>Proximity_Fault<span class="sc">+</span>Landuse_Vegetation<span class="sc">+</span>Precipitation<span class="sc">+</span>TWI<span class="sc">+</span>SPI<span class="sc">+</span>STI, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> Q6_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="generating-model-summary-5" class="level4">
<h4 class="anchored" data-anchor-id="generating-model-summary-5">4.6.1 Generating Model Summary</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_model_6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Landslide ~ Elevation + Slope_Angle + Aspect_North + 
    Aspect_NorthEast + Aspect_East + Aspect_SouthEast + Aspect_South + 
    Aspect_SouthWest + Aspect_West + Profile_Curvature + Plan_Curvature + 
    Lithology_Metamorphic + Lithology_Sedimentary + Lithology_Plutonic + 
    Lithology_Unconsolidated + Proximity_Settlement + Proximity_Stream + 
    Proximity_Road + Proximity_Fault + Landuse_Vegetation + Precipitation + 
    TWI + SPI + STI, family = "binomial", data = Q6_train)

Coefficients:
                           Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)              -3.111e+00  2.929e-01 -10.620  &lt; 2e-16 ***
Elevation                -1.726e-04  5.329e-05  -3.239 0.001199 ** 
Slope_Angle               2.361e-01  5.800e-03  40.716  &lt; 2e-16 ***
Aspect_North              9.442e-03  1.365e-01   0.069 0.944857    
Aspect_NorthEast         -3.125e-01  1.166e-01  -2.680 0.007354 ** 
Aspect_East              -3.556e-01  1.149e-01  -3.096 0.001965 ** 
Aspect_SouthEast         -3.969e-01  1.104e-01  -3.594 0.000326 ***
Aspect_South             -2.976e-01  1.087e-01  -2.738 0.006181 ** 
Aspect_SouthWest         -2.054e-01  1.107e-01  -1.856 0.063434 .  
Aspect_West              -2.140e-01  1.108e-01  -1.931 0.053435 .  
Profile_Curvature        -8.491e+02  3.187e+01 -26.645  &lt; 2e-16 ***
Plan_Curvature           -7.702e+02  3.809e+01 -20.222  &lt; 2e-16 ***
Lithology_Metamorphic     6.898e-01  1.587e-01   4.347 1.38e-05 ***
Lithology_Sedimentary     1.190e+00  1.643e-01   7.244 4.34e-13 ***
Lithology_Plutonic       -1.000e+00  1.522e-01  -6.573 4.92e-11 ***
Lithology_Unconsolidated  1.286e+00  1.591e-01   8.079 6.52e-16 ***
Proximity_Settlement      5.433e-05  4.772e-05   1.138 0.254925    
Proximity_Stream         -3.417e-03  2.511e-03  -1.361 0.173616    
Proximity_Road           -3.940e-03  1.682e-03  -2.342 0.019171 *  
Proximity_Fault           1.975e-05  2.817e-05   0.701 0.483310    
Landuse_Vegetation        6.864e-01  6.306e-02  10.885  &lt; 2e-16 ***
Precipitation            -6.012e+00  6.959e-01  -8.639  &lt; 2e-16 ***
TWI                      -2.416e-02  1.349e-02  -1.792 0.073210 .  
SPI                       2.185e+00  1.078e+00   2.027 0.042710 *  
STI                      -1.405e-03  1.234e-03  -1.139 0.254775    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 13449.2  on 9840  degrees of freedom
Residual deviance:  8076.3  on 9816  degrees of freedom
AIC: 8126.3

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
</section>
<section id="calculating-percentage-of-deviance-5" class="level4">
<h4 class="anchored" data-anchor-id="calculating-percentage-of-deviance-5">4.6.2 Calculating Percentage of Deviance</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span><span class="fu">with</span>(<span class="fu">summary</span>(log_model_6), <span class="dv">1</span> <span class="sc">-</span> deviance<span class="sc">/</span>null.deviance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39.94976</code></pre>
</div>
</div>
</section>
<section id="confusion-matrix-5" class="level4">
<h4 class="anchored" data-anchor-id="confusion-matrix-5">4.6.3 Confusion Matrix</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">blr_confusion_matrix</span>(log_model_6, <span class="at">cutoff =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics 

          Reference
Prediction    0    1
         0 4808  961
         1  801 3271

                Accuracy : 0.8210 
     No Information Rate : 0.5700 

                   Kappa : 0.6331 

McNemars's Test P-Value  : 2e-04 

             Sensitivity : 0.7729 
             Specificity : 0.8572 
          Pos Pred Value : 0.8033 
          Neg Pred Value : 0.8334 
              Prevalence : 0.4300 
          Detection Rate : 0.3324 
    Detection Prevalence : 0.4138 
       Balanced Accuracy : 0.8151 
               Precision : 0.8033 
                  Recall : 0.7729 

        'Positive' Class : 1</code></pre>
</div>
</div>
</section>
<section id="ploting-roc-curve-and-calculating-auc-5" class="level4">
<h4 class="anchored" data-anchor-id="ploting-roc-curve-and-calculating-auc-5">4.6.4 Ploting ROC Curve and Calculating AUC</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(log_model_6, Q6_test[, <span class="dv">6</span><span class="sc">:</span><span class="dv">29</span>], <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>roc_curve <span class="ot">&lt;-</span> <span class="fu">roc</span>(Q6_test<span class="sc">$</span>Landslide, predicted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the ROC curve</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc_curve, <span class="at">main =</span> <span class="st">"ROC Curve (Model 6)"</span>)</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray"</span>)  <span class="co"># Add a reference line for a random classifier</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slopesampling_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>auc_value <span class="ot">&lt;-</span> <span class="fu">auc</span>(roc_curve)</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AUC:"</span>, auc_value, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>AUC: 0.8919745 </code></pre>
</div>
</div>
</section>
</section>
<section id="logistic-regression-model-7-slope-cut-off-15" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression-model-7-slope-cut-off-15">4.7 Logistic Regression Model 7 (Slope Cut-off = 15)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>sample_Q7 <span class="ot">&lt;-</span> <span class="fu">subset</span>(train_grids_v4,Slope_Angle <span class="sc">&lt;</span> <span class="dv">15</span>)</span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(sample_Q7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9899</code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>sample_Q7, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">Slope_Angle</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#e9531e"</span>)<span class="sc">+</span></span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Slope Stratified Sampling (Cut-off 15)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slopesampling_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>), <span class="fu">nrow</span>(sample_Q7), <span class="at">replace=</span><span class="cn">TRUE</span>, <span class="at">prob=</span><span class="fu">c</span>(<span class="fl">0.70</span>,<span class="fl">0.30</span>))</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>Q7_train  <span class="ot">&lt;-</span> sample_Q7[sample, ]</span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a>Q7_test   <span class="ot">&lt;-</span> sample_Q7[<span class="sc">!</span>sample, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>log_model_7 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Landslide <span class="sc">~</span> Elevation <span class="sc">+</span> Slope_Angle <span class="sc">+</span> Aspect_North <span class="sc">+</span> Aspect_NorthEast <span class="sc">+</span> Aspect_East<span class="sc">+</span>Aspect_SouthEast<span class="sc">+</span>Aspect_South <span class="sc">+</span> Aspect_SouthWest <span class="sc">+</span>Aspect_West <span class="sc">+</span> Profile_Curvature <span class="sc">+</span>Plan_Curvature <span class="sc">+</span> Lithology_Metamorphic<span class="sc">+</span>Lithology_Sedimentary <span class="sc">+</span> Lithology_Plutonic<span class="sc">+</span>Lithology_Unconsolidated <span class="sc">+</span> Proximity_Settlement<span class="sc">+</span>Proximity_Stream<span class="sc">+</span>Proximity_Road<span class="sc">+</span>Proximity_Fault<span class="sc">+</span>Landuse_Vegetation<span class="sc">+</span>Precipitation<span class="sc">+</span>TWI<span class="sc">+</span>SPI<span class="sc">+</span>STI, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> Q7_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="generating-model-summary-6" class="level4">
<h4 class="anchored" data-anchor-id="generating-model-summary-6">4.7.1 Generating Model Summary</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_model_7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Landslide ~ Elevation + Slope_Angle + Aspect_North + 
    Aspect_NorthEast + Aspect_East + Aspect_SouthEast + Aspect_South + 
    Aspect_SouthWest + Aspect_West + Profile_Curvature + Plan_Curvature + 
    Lithology_Metamorphic + Lithology_Sedimentary + Lithology_Plutonic + 
    Lithology_Unconsolidated + Proximity_Settlement + Proximity_Stream + 
    Proximity_Road + Proximity_Fault + Landuse_Vegetation + Precipitation + 
    TWI + SPI + STI, family = "binomial", data = Q7_train)

Coefficients:
                           Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)              -2.802e+00  3.696e-01  -7.582 3.40e-14 ***
Elevation                -1.658e-04  6.253e-05  -2.652 0.007999 ** 
Slope_Angle               3.135e-01  9.170e-03  34.185  &lt; 2e-16 ***
Aspect_North              7.589e-02  1.727e-01   0.440 0.660267    
Aspect_NorthEast         -1.327e-01  1.445e-01  -0.918 0.358385    
Aspect_East              -3.560e-01  1.421e-01  -2.506 0.012225 *  
Aspect_SouthEast         -4.420e-01  1.381e-01  -3.200 0.001374 ** 
Aspect_South             -3.274e-01  1.330e-01  -2.463 0.013793 *  
Aspect_SouthWest         -4.410e-01  1.351e-01  -3.264 0.001100 ** 
Aspect_West              -2.250e-01  1.368e-01  -1.645 0.100035    
Profile_Curvature        -8.353e+02  3.826e+01 -21.832  &lt; 2e-16 ***
Plan_Curvature           -7.866e+02  4.896e+01 -16.066  &lt; 2e-16 ***
Lithology_Metamorphic     4.148e-01  2.310e-01   1.796 0.072535 .  
Lithology_Sedimentary     9.296e-01  2.386e-01   3.896 9.76e-05 ***
Lithology_Plutonic       -1.197e+00  2.131e-01  -5.619 1.93e-08 ***
Lithology_Unconsolidated  1.029e+00  2.311e-01   4.451 8.53e-06 ***
Proximity_Settlement     -3.104e-05  6.156e-05  -0.504 0.614045    
Proximity_Stream         -5.147e-03  3.221e-03  -1.598 0.110040    
Proximity_Road           -1.861e-03  2.165e-03  -0.860 0.389909    
Proximity_Fault          -9.501e-06  3.626e-05  -0.262 0.793311    
Landuse_Vegetation        5.228e-01  7.716e-02   6.776 1.24e-11 ***
Precipitation            -6.391e+00  8.730e-01  -7.321 2.46e-13 ***
TWI                      -5.090e-02  1.507e-02  -3.377 0.000734 ***
SPI                       1.379e+00  1.340e+00   1.030 0.303151    
STI                      -2.907e-04  1.653e-03  -0.176 0.860400    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 8845.5  on 6951  degrees of freedom
Residual deviance: 5320.6  on 6927  degrees of freedom
AIC: 5370.6

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
</section>
<section id="calculating-percentage-of-deviance-6" class="level4">
<h4 class="anchored" data-anchor-id="calculating-percentage-of-deviance-6">4.7.2 Calculating Percentage of Deviance</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span><span class="fu">with</span>(<span class="fu">summary</span>(log_model_7), <span class="dv">1</span> <span class="sc">-</span> deviance<span class="sc">/</span>null.deviance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39.84979</code></pre>
</div>
</div>
</section>
<section id="confusion-matrix-6" class="level4">
<h4 class="anchored" data-anchor-id="confusion-matrix-6">4.7.3 Confusion Matrix</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">blr_confusion_matrix</span>(log_model_7, <span class="at">cutoff =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics 

          Reference
Prediction    0    1
         0 4209  696
         1  429 1618

                Accuracy : 0.8382 
     No Information Rate : 0.6671 

                   Kappa : 0.6248 

McNemars's Test P-Value  : 0.0000 

             Sensitivity : 0.6992 
             Specificity : 0.9075 
          Pos Pred Value : 0.7904 
          Neg Pred Value : 0.8581 
              Prevalence : 0.3329 
          Detection Rate : 0.2327 
    Detection Prevalence : 0.2944 
       Balanced Accuracy : 0.8034 
               Precision : 0.7904 
                  Recall : 0.6992 

        'Positive' Class : 1</code></pre>
</div>
</div>
</section>
<section id="ploting-roc-curve-and-calculating-auc-6" class="level4">
<h4 class="anchored" data-anchor-id="ploting-roc-curve-and-calculating-auc-6">4.7.4 Ploting ROC Curve and Calculating AUC</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(log_model_7, Q7_test[, <span class="dv">6</span><span class="sc">:</span><span class="dv">29</span>], <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>roc_curve <span class="ot">&lt;-</span> <span class="fu">roc</span>(Q7_test<span class="sc">$</span>Landslide, predicted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the ROC curve</span></span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc_curve, <span class="at">main =</span> <span class="st">"ROC Curve (Model 7)"</span>)</span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray"</span>)  <span class="co"># Add a reference line for a random classifier</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slopesampling_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>auc_value <span class="ot">&lt;-</span> <span class="fu">auc</span>(roc_curve)</span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AUC:"</span>, auc_value, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>AUC: 0.8799747 </code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="geographically-weighted-logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="geographically-weighted-logistic-regression">5.0 Geographically Weighted Logistic Regression</h2>
<p>Next, we will run Geographically Weighted Logistic Regression (GWLR) models using <code>sample_Q5</code> dataset and <code>GWmodel</code> package. In order to perform GWLR modelling in <code>GWmodel</code>, we will first need to convert <em>t</em>he datasets into a <strong>SpatialPointsDataFrame</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>sample_Q5.sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(sample_Q5,</span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"X"</span>, <span class="st">"Y"</span>))</span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a>sample_Q5.sf <span class="ot">&lt;-</span> <span class="fu">st_set_crs</span>(sample_Q5.sf, <span class="dv">32632</span>)</span>
<span id="cb123-4"><a href="#cb123-4" aria-hidden="true" tabindex="-1"></a>sample_Q5.sp <span class="ot">&lt;-</span> sample_Q5.sf <span class="sc">%&gt;%</span> <span class="fu">as_Spatial</span>()</span>
<span id="cb123-5"><a href="#cb123-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-6"><a href="#cb123-6" aria-hidden="true" tabindex="-1"></a>Q5_train.sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(Q5_train,</span>
<span id="cb123-7"><a href="#cb123-7" aria-hidden="true" tabindex="-1"></a>                            <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"X"</span>, <span class="st">"Y"</span>))</span>
<span id="cb123-8"><a href="#cb123-8" aria-hidden="true" tabindex="-1"></a>Q5_train.sf <span class="ot">&lt;-</span> <span class="fu">st_set_crs</span>(Q5_train.sf, <span class="dv">32632</span>)</span>
<span id="cb123-9"><a href="#cb123-9" aria-hidden="true" tabindex="-1"></a>Q5_train.sp <span class="ot">&lt;-</span> Q5_train.sf <span class="sc">%&gt;%</span> <span class="fu">as_Spatial</span>()</span>
<span id="cb123-10"><a href="#cb123-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-11"><a href="#cb123-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-12"><a href="#cb123-12" aria-hidden="true" tabindex="-1"></a>Q5_test.sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(Q5_test,</span>
<span id="cb123-13"><a href="#cb123-13" aria-hidden="true" tabindex="-1"></a>                            <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"X"</span>, <span class="st">"Y"</span>))</span>
<span id="cb123-14"><a href="#cb123-14" aria-hidden="true" tabindex="-1"></a>Q5_test.sf <span class="ot">&lt;-</span> <span class="fu">st_set_crs</span>(Q5_test.sf, <span class="dv">32632</span>)</span>
<span id="cb123-15"><a href="#cb123-15" aria-hidden="true" tabindex="-1"></a>Q5_test.sp <span class="ot">&lt;-</span> Q5_test.sf <span class="sc">%&gt;%</span> <span class="fu">as_Spatial</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will make a quick plot to see the geographical distribution of landslide and non-landslide samples in <code>sample_Q5</code>.</p>
<section id="calculating-adaptive-bandwidth" class="level3">
<h3 class="anchored" data-anchor-id="calculating-adaptive-bandwidth">5.1 Calculating Adaptive Bandwidth</h3>
<p>In this section, we will calculate the adaptive bandwidth for fitting a GWLE model using the <strong><code>bw.ggwr</code></strong> function from <code>GWmodel</code>.</p>
<p>Firstly, we will create a distance matrix to be used for calculating the bandwidth. The <strong><code>st_coordinates</code></strong> function is used to extract the coordinates from the <strong><code>Q5_train.sf</code></strong> spatial object. The <strong><code>gw.dist</code></strong> function is then used to calculate the distance matrix <strong><code>dist.test</code></strong> based on these coordinates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>dist_mat <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(Q5_train.sf) </span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a>dist.test <span class="ot">&lt;-</span> <span class="fu">gw.dist</span>(<span class="at">dp.locat=</span>dist_mat,<span class="at">p=</span><span class="dv">2</span>, <span class="at">theta=</span><span class="dv">0</span>, <span class="at">longlat=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that, we have created the distance matrix, we will calculate the adaptive bandwidth value with specifications as below.</p>
<ul>
<li><p>The <strong><code>family</code></strong> argument is set to <strong><code>"binomial"</code></strong>, indicating that a binomial distribution is assumed for the dependent variable.</p></li>
<li><p>The <strong><code>approach</code></strong> argument is set to <strong><code>"CV"</code></strong>, indicating that cross-validation is used for bandwidth selection.</p></li>
<li><p>The <strong><code>kernel</code></strong> argument is set to <strong><code>"gaussian"</code></strong>, indicating that a Gaussian kernel function is used.</p></li>
<li><p>The <strong><code>adaptive</code></strong> argument is set to <strong><code>TRUE</code></strong>, indicating that an adaptive kernel is used, where the bandwidth corresponds to the number of nearest neighbors.</p></li>
<li><p>The <strong><code>p</code></strong> and <strong><code>theta</code></strong> arguments are set to <strong><code>2</code></strong> and <strong><code>0</code></strong> respectively, which are the default values for the power of the Minkowski distance and the angle to rotate the coordinate system.</p></li>
<li><p>The <strong><code>longlat</code></strong> argument is set to <strong><code>FALSE</code></strong>, indicating that Euclidean distances are calculated.</p></li>
<li><p>Finally, the <strong><code>dMat</code></strong> argument is set to <strong><code>dist.test</code></strong>, which is the pre-specified distance matrix that we calculated earlier.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>adaptive_bw <span class="ot">&lt;-</span> <span class="fu">bw.ggwr</span>(Landslide <span class="sc">~</span> Elevation <span class="sc">+</span> Slope_Angle <span class="sc">+</span> Aspect_North <span class="sc">+</span> Aspect_NorthEast <span class="sc">+</span> Aspect_East<span class="sc">+</span>Aspect_SouthEast<span class="sc">+</span>Aspect_South <span class="sc">+</span> Aspect_SouthWest <span class="sc">+</span>Aspect_West <span class="sc">+</span> Profile_Curvature <span class="sc">+</span>Plan_Curvature <span class="sc">+</span> Lithology_Metamorphic<span class="sc">+</span>Lithology_Sedimentary <span class="sc">+</span> Lithology_Plutonic<span class="sc">+</span>Lithology_Unconsolidated <span class="sc">+</span> Proximity_Settlement<span class="sc">+</span>Proximity_Stream<span class="sc">+</span>Proximity_Road<span class="sc">+</span>Proximity_Fault<span class="sc">+</span>Landuse_Vegetation<span class="sc">+</span>Precipitation<span class="sc">+</span>TWI<span class="sc">+</span>SPI<span class="sc">+</span>STI, <span class="at">data =</span> Q5_train_sp, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">approach=</span><span class="st">"CV"</span>, <span class="at">kernel=</span><span class="st">"gaussian"</span>,</span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">adaptive=</span><span class="cn">TRUE</span>, <span class="at">p=</span><span class="dv">2</span>, <span class="at">theta=</span><span class="dv">0</span>, <span class="at">longlat=</span>F, <span class="at">dMat=</span>dist.test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/Screenshot 2024-02-19 at 9.56.31 PM.png" class="img-fluid"></p>
<p>Based on the result, the optimal adaptive bandwidth value that yields the lowest CV score is <strong>203</strong> (with CV score = 1312.815). We will use this value in fitting GWLR model <code>gwlr</code>.</p>
</section>
<section id="building-geographically-weighted-logistic-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="building-geographically-weighted-logistic-regression-model">5.2 Building Geographically Weighted Logistic Regression Model</h3>
<p>We will use <code>ggwr.basic()</code> function from <code>GWmodel</code> package to fit a GWLR model <code>gwlr</code> using the specifications below.</p>
<ul>
<li><p>The <strong><code>bw</code></strong> argument is set to <strong><code>203</code></strong>, which is the optimal adaptive bandwidth value that yields the lowest CV score (1312.815). This value was determined in a previous step.</p></li>
<li><p>The <strong><code>family</code></strong> argument is set to <strong><code>"binomial"</code></strong>, indicating that a binomial distribution is assumed for the dependent variable. The <strong><code>kernel</code></strong> argument is set to <strong><code>"gaussian"</code></strong>, indicating that a Gaussian kernel function is used.</p></li>
<li><p>The <strong><code>adaptive</code></strong> argument is set to <strong><code>TRUE</code></strong>, indicating that an adaptive kernel is used, where the bandwidth corresponds to the number of nearest neighbors. The <strong><code>cv</code></strong> argument is set to <strong><code>TRUE</code></strong>, indicating that cross-validation data will be calculated.</p></li>
<li><p>The <strong><code>tol</code></strong> argument is set to <strong><code>0.00001</code></strong>, which is the threshold that determines the convergence of the IRLS procedure.</p></li>
<li><p>The <strong><code>p</code></strong> and <strong><code>theta</code></strong> arguments are set to <strong><code>2</code></strong> and <strong><code>0</code></strong> respectively, which are the default values for the power of the Minkowski distance and the angle to rotate the coordinate system.</p></li>
<li><p>The <strong><code>longlat</code></strong> argument is set to <strong><code>FALSE</code></strong>, indicating that Euclidean distances are calculated.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>gwlr <span class="ot">&lt;-</span> <span class="fu">ggwr.basic</span>(Landslide <span class="sc">~</span> Elevation <span class="sc">+</span> Slope_Angle <span class="sc">+</span> Aspect_North <span class="sc">+</span> Aspect_NorthEast <span class="sc">+</span> Aspect_East<span class="sc">+</span>Aspect_SouthEast<span class="sc">+</span>Aspect_South <span class="sc">+</span> Aspect_SouthWest <span class="sc">+</span>Aspect_West <span class="sc">+</span> Profile_Curvature <span class="sc">+</span>Plan_Curvature <span class="sc">+</span> Lithology_Metamorphic<span class="sc">+</span>Lithology_Sedimentary <span class="sc">+</span> Lithology_Plutonic<span class="sc">+</span>Lithology_Unconsolidated <span class="sc">+</span> Proximity_Settlement<span class="sc">+</span>Proximity_Stream<span class="sc">+</span>Proximity_Road<span class="sc">+</span>Proximity_Fault<span class="sc">+</span>Landuse_Vegetation<span class="sc">+</span>Precipitation<span class="sc">+</span>TWI<span class="sc">+</span>SPI<span class="sc">+</span>STI, <span class="at">data =</span> Q5_train_sp, <span class="at">regression.points =</span> Q5_test_sp, <span class="at">bw=</span> <span class="dv">203</span>, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">kernel =</span> <span class="st">"gaussian"</span>, <span class="at">adaptive =</span> <span class="cn">TRUE</span>, <span class="at">cv =</span> T, <span class="at">tol =</span> <span class="fl">0.00001</span>, <span class="at">p =</span> <span class="dv">2</span>, <span class="at">theta =</span> <span class="dv">0</span>, <span class="at">longlat =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="model-summary" class="level3">
<h3 class="anchored" data-anchor-id="model-summary">5.3 Model Summary</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>gwlr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ***********************************************************************
   *                       Package   GWmodel                             *
   ***********************************************************************
   Program starts at: 2024-02-20 08:43:41.302803 
   Call:
   ggwr.basic(formula = Landslide ~ Elevation + Slope_Angle + Aspect_North + 
    Aspect_NorthEast + Aspect_East + Aspect_SouthEast + Aspect_South + 
    Aspect_SouthWest + Aspect_West + Profile_Curvature + Plan_Curvature + 
    Lithology_Metamorphic + Lithology_Sedimentary + Lithology_Plutonic + 
    Lithology_Unconsolidated + Proximity_Settlement + Proximity_Stream + 
    Proximity_Road + Proximity_Fault + Landuse_Vegetation + Precipitation + 
    TWI + SPI + STI, data = Q5_train_sp, regression.points = Q5_test_sp, 
    bw = 203, family = "binomial", kernel = "gaussian", adaptive = TRUE, 
    cv = T, tol = 1e-05, p = 2, theta = 0, longlat = FALSE)

   Dependent (y) variable:  Landslide
   Independent variables:  Elevation Slope_Angle Aspect_North Aspect_NorthEast Aspect_East Aspect_SouthEast Aspect_South Aspect_SouthWest Aspect_West Profile_Curvature Plan_Curvature Lithology_Metamorphic Lithology_Sedimentary Lithology_Plutonic Lithology_Unconsolidated Proximity_Settlement Proximity_Stream Proximity_Road Proximity_Fault Landuse_Vegetation Precipitation TWI SPI STI
   Number of data points: 12936
   Used family: binomial
   ***********************************************************************
   *              Results of Generalized linear Regression               *
   ***********************************************************************

Call:
NULL

Coefficients:
                           Estimate Std. Error z value Pr(&gt;|z|)    
Intercept                -3.437e+00  2.804e-01 -12.255  &lt; 2e-16 ***
Elevation                -2.053e-04  5.153e-05  -3.983 6.80e-05 ***
Slope_Angle               2.564e-01  4.957e-03  51.712  &lt; 2e-16 ***
Aspect_North              6.226e-02  1.286e-01   0.484   0.6284    
Aspect_NorthEast         -9.202e-02  1.092e-01  -0.843   0.3993    
Aspect_East              -1.559e-01  1.083e-01  -1.439   0.1501    
Aspect_SouthEast         -2.629e-01  1.050e-01  -2.505   0.0123 *  
Aspect_South             -2.082e-01  1.023e-01  -2.036   0.0417 *  
Aspect_SouthWest         -6.468e-02  1.051e-01  -0.615   0.5383    
Aspect_West              -4.534e-02  1.056e-01  -0.430   0.6675    
Profile_Curvature        -8.460e+02  3.008e+01 -28.120  &lt; 2e-16 ***
Plan_Curvature           -7.246e+02  3.422e+01 -21.173  &lt; 2e-16 ***
Lithology_Metamorphic     7.394e-01  1.392e-01   5.313 1.08e-07 ***
Lithology_Sedimentary     1.098e+00  1.447e-01   7.588 3.24e-14 ***
Lithology_Plutonic       -6.174e-01  1.322e-01  -4.671 2.99e-06 ***
Lithology_Unconsolidated  1.305e+00  1.404e-01   9.294  &lt; 2e-16 ***
Proximity_Settlement      7.413e-05  4.614e-05   1.607   0.1081    
Proximity_Stream         -5.654e-03  2.351e-03  -2.405   0.0162 *  
Proximity_Road           -3.436e-03  1.607e-03  -2.138   0.0325 *  
Proximity_Fault           2.964e-05  2.555e-05   1.160   0.2462    
Landuse_Vegetation        6.619e-01  5.991e-02  11.048  &lt; 2e-16 ***
Precipitation            -5.054e+00  6.600e-01  -7.657 1.90e-14 ***
TWI                      -2.496e-02  1.328e-02  -1.880   0.0601 .  
SPI                       5.565e-01  9.392e-01   0.593   0.5535    
STI                       1.216e-04  1.135e-03   0.107   0.9147    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 17778.2  on 12935  degrees of freedom
Residual deviance:  9367.3  on 12911  degrees of freedom
AIC: 9417.3

Number of Fisher Scoring iterations: 6


 AICc:  9417.362
 Pseudo R-square value:  0.4731051
   ***********************************************************************
   *          Results of Geographically Weighted Regression              *
   ***********************************************************************

   *********************Model calibration information*********************
   Kernel function: gaussian 
   Adaptive bandwidth: 203 (number of nearest neighbours)
   Regression points: A seperate set of regression points is used.
   Distance metric: Euclidean distance metric is used.

   ************Summary of Generalized GWR coefficient estimates:**********
                                   Min.     1st Qu.      Median     3rd Qu.
   Intercept                -2.2292e+03 -4.7322e+00 -2.4838e+00  1.1179e+00
   Elevation                -5.5303e-03 -1.9487e-03 -1.0699e-03 -3.9695e-04
   Slope_Angle               1.3679e-01  2.3957e-01  2.6247e-01  3.0523e-01
   Aspect_North             -3.2685e+00 -3.7158e-01  6.6438e-02  5.7209e-01
   Aspect_NorthEast         -2.0677e+00 -5.3232e-01 -5.1641e-02  4.9088e-01
   Aspect_East              -2.2102e+00 -6.6302e-01 -1.2399e-01  5.9538e-01
   Aspect_SouthEast         -2.2022e+00 -7.7883e-01 -7.5033e-02  6.4405e-01
   Aspect_South             -2.7350e+00 -6.9757e-01 -1.2606e-01  5.8518e-01
   Aspect_SouthWest         -2.1135e+00 -5.8536e-01 -1.6144e-01  3.7881e-01
   Aspect_West              -2.1831e+00 -4.1492e-01 -9.8628e-02  4.2942e-01
   Profile_Curvature        -1.4988e+03 -8.7123e+02 -7.1415e+02 -5.6137e+02
   Plan_Curvature           -2.3965e+03 -1.0010e+03 -7.7246e+02 -5.5740e+02
   Lithology_Metamorphic    -4.0714e+02 -1.5267e+00 -4.2470e-01  5.1771e-01
   Lithology_Sedimentary    -4.0603e+02 -1.7469e+00 -3.9433e-01  7.4777e-01
   Lithology_Plutonic       -9.0420e+00 -3.6743e+00 -1.4776e+00 -3.0875e-01
   Lithology_Unconsolidated -4.0720e+02 -1.3369e+00  2.2028e-01  1.0894e+00
   Proximity_Settlement     -1.1802e-03 -3.0190e-05  2.0770e-04  6.3443e-04
   Proximity_Stream         -1.5947e-01 -3.6857e-02 -8.1638e-03  1.9761e-02
   Proximity_Road           -9.5281e-02 -1.3754e-02 -7.6464e-04  1.6616e-02
   Proximity_Fault          -2.6713e-03 -2.4192e-04  8.0035e-05  4.6317e-04
   Landuse_Vegetation       -7.7653e-01  6.7617e-02  5.2753e-01  9.0657e-01
   Precipitation            -7.9766e+01 -4.5176e+00  7.8831e+00  1.7006e+01
   TWI                      -4.0499e-01 -1.4649e-01 -7.6203e-02 -2.0298e-02
   SPI                      -1.8961e+01 -2.8786e+00  7.3061e-01  4.0492e+00
   STI                      -1.4056e-02 -3.0657e-03  1.5789e-03  5.7384e-03
                                 Max.
   Intercept                 412.2115
   Elevation                   0.0028
   Slope_Angle                 0.5331
   Aspect_North                3.2800
   Aspect_NorthEast            1.9637
   Aspect_East                 2.5205
   Aspect_SouthEast            2.3429
   Aspect_South                3.4021
   Aspect_SouthWest            2.6369
   Aspect_West                 2.2829
   Profile_Curvature         161.7406
   Plan_Curvature            402.5170
   Lithology_Metamorphic    2277.2060
   Lithology_Sedimentary    2169.7130
   Lithology_Plutonic          1.3806
   Lithology_Unconsolidated 2180.1257
   Proximity_Settlement        0.0023
   Proximity_Stream            0.1261
   Proximity_Road              0.0846
   Proximity_Fault             0.0021
   Landuse_Vegetation          2.4352
   Precipitation              57.6561
   TWI                         0.3045
   SPI                        28.0687
   STI                         0.0302
   ************************Diagnostic information*************************

   ***********************************************************************
   Program stops at: 2024-02-20 09:14:42.8669 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>gwlr<span class="sc">$</span>glms<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Intercept                Elevation              Slope_Angle 
           -3.436770e+00            -2.052627e-04             2.563553e-01 
            Aspect_North         Aspect_NorthEast              Aspect_East 
            6.226444e-02            -9.202286e-02            -1.558962e-01 
        Aspect_SouthEast             Aspect_South         Aspect_SouthWest 
           -2.629472e-01            -2.082398e-01            -6.468301e-02 
             Aspect_West        Profile_Curvature           Plan_Curvature 
           -4.534026e-02            -8.459590e+02            -7.246333e+02 
   Lithology_Metamorphic    Lithology_Sedimentary       Lithology_Plutonic 
            7.393810e-01             1.098101e+00            -6.173966e-01 
Lithology_Unconsolidated     Proximity_Settlement         Proximity_Stream 
            1.304713e+00             7.412645e-05            -5.654027e-03 
          Proximity_Road          Proximity_Fault       Landuse_Vegetation 
           -3.435956e-03             2.963535e-05             6.619341e-01 
           Precipitation                      TWI                      SPI 
           -5.053843e+00            -2.495763e-02             5.565392e-01 
                     STI 
            1.216127e-04 </code></pre>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">What Causes Landslides? Explanatory Landslide Susceptibility Modelling of Valtellina Valley, Lombardy Region, Italy</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>